### ISSUE TITLE
Is it possible to change the database name?

### ISSUE THREAD

**Issue by vrfvitor** [zonkyio/embedded-database-spring-test#151]
I'm running the liquibase migrations in zonky postgres embedded database and facing "cross-database references" problems because in some of the scripts there are explicit references to the staging and production db name.
Is there a way I could fix it by changing its name using a zonky property or specific configuration?

**Comment by tomix26** [comment]
Do you mean a cross-catalog or cross-cluster reference? And what kind of method do you use for that? Postgres foreign-data wrapper, dblink extension, or something else? Could you also please provide an example of the query or migration?

**Comment by vrfvitor** [comment]
No, that's actually way simpler. Let's say my production database is named "app_db" and I use its public schema, then in a few migration sql files I have something like "DELETE FROM app_db.public.Foo WHERE id = 1" so I would like to change zonky's db name to match production's (instead of a random one) and avoid the "cross-database references are not implemented" error without changing the migration files. Is there a config for this?

**Comment by tomix26** [comment]
Ok, now I get it. Unfortunately, database names are generated automatically and cannot be changed. It's because multiple independent databases can be created within a single build and this prevents name collisions.

So, in your case, I recommend changing the migration and removing the database name from the query. Because this information is redundant and only complicates the portability of the sql migrations.

Alternatively, you can use the `current_database()` function to get the name of the current database and use it in a dynamic query. Nevertheless, it still requires a change in sql migrations.

**Comment by vrfvitor** [comment]
For sure, our way of doing things wasn't the best possible and we'll be looking for solutions in our side. Appreciate your time answering me and allocated to such an usefull project. Thanks!
