### ISSUE TITLE
Upgrade flyway-core and flyway-spring-test dependencies to version 7

### ISSUE THREAD

**Issue by Groosling** [zonkyio/embedded-database-spring-test#154]
Hi guys,
We have recently upgraded to spring boot to 2.4.2 and what we noticed is that comes with dependency **flyway-core:7.1.1**.
  
Would it it possible to to upgrade to both **flyway-core 7** and **flyway-spring-test 7** on your side, too?

Since **embedded-database-spring-test** uses flyway-core:5.0.7 and **flyway-spring-test:5.0.0**, it's working together only with workaround (adding this dependency explicitly to our project):
```
api "org.flywaydb.flyway-test-extensions:flyway-spring-test:7.0.0"
```

**Comment by tomix26** [comment]
Hi, the problem is that spring boot comes with a dependency for `flyway-core` but not for `flyway-spring-test`. So whatever I do, there always be someone whose versions do not match. The only solution is to make the flyway dependencies optional, which will be implemented in version 2.0.0. For now, [2.0.0-beta1](https://github.com/zonkyio/embedded-database-spring-test/releases/tag/v2.0.0-beta1) is available for testing, so you can try it and give me feedback.
