### ISSUE TITLE
Embedded Postgres Database without Docker?

### ISSUE THREAD

**Issue by Mom0aut** [zonkyio/embedded-database-spring-test#156]
Hello,

just as the title says can i run an embedded Postgres Database without a Docker Environment?

best regards Mom0

**Comment by Mom0aut** [comment]
i downgraded to some older version this fixed my issue

**Comment by tomix26** [comment]
Hi, since version 2.0.0, the docker is a default provider. But it's possible to change that by setting `zonky.test.database.provider=zonky` property and adding `io.zonky.test:embedded-postgres` dependency.

More info here: https://github.com/zonkyio/embedded-database-spring-test/tree/2.0.x#using-zonky-provider-previous-default
