### ISSUE TITLE
Enable and Disable EmbeddedDatabase with Settings or Profile?

### ISSUE THREAD

**Issue by Mom0aut** [zonkyio/embedded-database-spring-test#159]
Hey is it possible to disable and enable the EmbeddedDatabase in specific Spring Profiles or Settings?

Like i have multiple Profiles:
- Test Profile: Disable EmbeddedDatabase
- QS Profile: Enable EmbeddedDatabase

Regards Mom0

**Comment by tomix26** [comment]
Hi, since version 2.0 you can use `zonky.test.database.replace` property to do that. Just add `zonky.test.database.replace=none` to your test profile configuration and `zonky.test.database.replace=any` to the QS profile configuration.

**Comment by Mom0aut** [comment]
Thank you for your fast response. I updated to version 2.0.0-beta1 but the properties didnt effect the embedded Database Settings.

I tried following properties:
- zonky.test.database.replace=none
- zonky.test.database.provider=zonky

We use custom property sources, maybe thats why the properties are not detected.
Is it possible to load some extra file for the property definition or can i change the property via the pom file?

**Comment by tomix26** [comment]
If the custom property sources are registered properly before `BeanDefinitionRegistryPostProcessor#postProcessBeanDefinitionRegistry` phase, it should not be a problem.

Could you please provide a logfile with enabled debug logging?

It should also be possible to set the property as an environment variable `ZONKY_TEST_DATABASE_REPLACE=XXX`. If you are using maven failsafe plugin, you can set it via [environmentVariables](https://maven.apache.org/surefire/maven-failsafe-plugin/integration-test-mojo.html#environmentVariables) parameter, or even pass it as system property in [argLine](https://maven.apache.org/surefire/maven-failsafe-plugin/integration-test-mojo.html#argLine) string.

**Comment by Mom0aut** [comment]
Thank you for your response, it is now working with the argline -Dzonky.test.database.replace=none/any.

**Comment by nbabb** [comment]
I have tried using the above property, either from the command line or via application.yaml (in a spring boot application), and am not getting quite the expected behavior.  What we want is for the embedded db to be used only in certain cases, and by default we want to use an actual db.

So we have spring setup with a datasource
```
spring:
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
```
and then our test class is annotated with `@AutoConfigureEmbeddedDatabase(provider = ZONKY, type = POSTGRES)`

With the property set to `NONE`
```
zonky:
  test:
    database:
      replace: NONE
```      
  
I end up with errors in spring
```
Caused by: org.flywaydb.core.api.FlywayException: Unable to connect to the database. Configure the url, user and password!
	at org.flywaydb.core.internal.configuration.ConfigurationValidator.validate(ConfigurationValidator.java:34)
	at org.flywaydb.core.Flyway.execute(Flyway.java:416)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:159)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet
```
where if I simply comment out the `@AutoConfigureEmbeddedDatabase` annotation the test runs fine.  I do see the log message set `The use of the embedded database has been disabled` when I set to NONE.

Any thoughts on this (or alternatives to consider)?  Thanks.

**Comment by tomix26** [comment]
Hi @nbabb, thanks for the report, it's a bug in auto-configurations. There's no easy workaround for that, so I'll try to release a fixed version as soon as possible. I've also created a new issue #163 because this bug is not related to the original report.

**Comment by nbabb** [comment]
Great, thanks for the quick turnaround on this issue @tomix26.  Any rough ETA on a new release?
