### ISSUE TITLE
uuid-ossp in postgres < 11.6

### ISSUE THREAD

**Issue by jajcek** [zonkyio/embedded-database-spring-test#86]
Hi,

when using zonky provider with BOM binaries in version < 11.6 I'm getting error thrown from flyway 5.2.4 migration (because we're using uuid-ossp extension):

ERROR: could not load library "/tmp/embedded-pg/PG-abd59c6e534f18097fa5675dc49b6fff/lib/postgresql/uuid-ossp.so": libossp-uuid.so.16: cannot open shared object file: No such file or directory

but it works in version > 11.6. Are you aware of this problem? Also in the Zonky documentation it says that extensions are not supported for zonky provider. Why it actually works in higher versions?

Thanks,
Jacek

**Comment by tomix26** [comment]
Yes, this issue has been fixed in version `11.6.0`. Is is mentioned in release notes: https://github.com/zonkyio/embedded-postgres-binaries/releases/tag/v11.6.0

Regarding the extensions, only 3rd party extensions are not supported, but all extensions from [contrib modules](https://www.postgresql.org/docs/current/contrib.html) are supported.
